# A Pod that runs nginx
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    fruit: apple
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
