apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 9200
    name: rest
  - port: 9300
    name: transport
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      terminationGracePeriodSeconds: 5
      volumes:
        - name: plugins
          emptyDir: {}
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: elasticsearch-config
        - name: pki
          configMap:
            name: searchguard-pki
        - name: searchguard-config
          configMap:
            name: searchguard-config
        - name: searchguard-loader
          configMap:
            name: searchguard-loader
      initContainers:
        - name: sysctl
          image: busybox
          command:
          - sh
          - -c
          - sysctl -w vm.max_map_count=262144 && ulimit -n 65536
          securityContext:
            privileged: true
        - name: plugins
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
          command:
            - sh
            - -c
            - |
              bin/elasticsearch-plugin install -b https://download.support.siren.io/federate/7.17.1-27.2.zip &&
              bin/elasticsearch-plugin install -b https://maven.search-guard.com//search-guard-suite-release/com/floragunn/search-guard-suite-plugin/7.17.1-53.1.0/search-guard-suite-plugin-7.17.1-53.1.0.zip
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/plugins/
              name: plugins
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9200
          - containerPort: 9300
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 2Gi
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_HOME
              value: /usr/share/elasticsearch/jdk
          volumeMounts:
            - name: plugins
              mountPath: /usr/share/elasticsearch/plugins
            - name: data
              mountPath: /usr/share/elasticsearch/data
            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
              readOnly: true
            - name: pki
              mountPath: /usr/share/elasticsearch/config/pki/
              readOnly: true
            - name: searchguard-config
              mountPath: /tmp/sgconfig/
              readOnly: true
            - name: searchguard-loader
              mountPath: /tmp/loader.sh
              readOnly: true
              subPath: loader.sh
          livenessProbe:
            tcpSocket:
              port: 9300
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - bash
                - /tmp/loader.sh
            initialDelaySeconds: 40
            timeoutSeconds: 10
            periodSeconds: 10
